# Generated by Django 4.2.7 on 2023-11-18 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Author's full name", max_length=255)),
                ('birth_date', models.DateField(blank=True, help_text="Author's birth date", null=True)),
                ('biography', models.TextField(blank=True, help_text="Author's biography")),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the book', max_length=255)),
                ('reviewer_name', models.CharField(help_text='Name of the reviewer', max_length=255)),
                ('content', models.TextField(help_text='Review content')),
                ('rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='Rating: from 1 to 5')),
                ('author', models.ForeignKey(help_text='Foreign key to the Author model', on_delete=django.db.models.deletion.CASCADE, to='Author.author')),
            ],
        ),
    ]
